-- phpMyAdmin SQL Dump
-- version 4.4.10
-- http://www.phpmyadmin.net
--
-- Client :  localhost:3306
-- Généré le :  Mer 14 Décembre 2016 à 14:26
-- Version du serveur :  5.5.42
-- Version de PHP :  5.6.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données :  `cinebo`
--

-- --------------------------------------------------------

--
-- Structure de la table `filmuz`
--

CREATE TABLE `filmuz` (
  `id` int(11) NOT NULL,
  `type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `titre` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `playlist` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `image` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `annee` int(11) NOT NULL,
  `compositeur` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `compobio` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `visible` int(11) NOT NULL DEFAULT '1'
) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Contenu de la table `filmuz`
--

INSERT INTO `filmuz` (`id`, `type`, `titre`, `playlist`, `image`, `annee`, `compositeur`, `compobio`, `visible`) VALUES
(1, 'western', 'Le Bon, la Brute et le Truand', 'https://embed.spotify.com/?uri=spotify%3Aalbum%3A4oaRhedDQNts1bR51IoATb\n', 'img-content/western/lebonlabruteletruand.jpg', 1968, 'Ennio Morricone', 'Ennio Morricone, né en 1928, est un compositeur, producteur et chef d''orchestre italien. Il est particulièrement connu pour ses musiques de films, notamment les films de son ami Sergio Leone. Ayant composé la musique de plus de 500 films et récompensé 25 fois dans divers cérémonies dans la catégorie « Meilleure musique de film », sa dernière récompense fut pour le film « Les Huit Salopards » (2015) de Quentin Tarantino.', 0),
(2, 'western', 'Il était une fois dans l''Ouest', 'https://embed.spotify.com/?uri=spotify%3Aalbum%3A2nevnh4rJIOOCUylrgQKEv', 'img-content/western/iletaitunefois-ouest.jpg', 1969, 'Ennio Morricone', 'Ennio Morricone, né en 1928, est un compositeur, producteur et chef d''orchestre italien. Il est particulièrement connu pour ses musiques de films, notamment les films de son ami Sergio Leone. Ayant composé la musique de plus de 500 films et récompensé 25 fois dans divers cérémonies dans la catégorie « Meilleure musique de film », sa dernière récompense fut pour le film « Les Huit Salopards » (2015) de Quentin Tarantino.', 0),
(3, 'western', '3h10 pour Yuma', 'https://embed.spotify.com/?uri=spotify%3Atrack%3A4NlRXcD9C9tb2ZoI6HBtGg', 'img-content/western/310-yuma.jpg', 2007, 'Marco Beltrami', 'Marco Edward Beltrami (né le 7 octobre 1966 à Long Island, New York) est un compositeur américain. Il suivi les cours de composition de musique de films dispensés par le maestro Jerry Goldsmith. Il se fait connaître par le succès de Scream en 1996. Dès lors, il alterne les films fantastiques et les thrillers mais sa musique prend une dimension dramatique plus aboutie avec les westerns que sont Trois enterrements et 3h10 pour Yuma, pour lequel il obtient sa première nomination à l''Oscar de la meilleure musique.', 0),
(4, 'western', 'Mon nom est personne', 'https://embed.spotify.com/?uri=spotify%3Aalbum%3A70GTqZqPaPQmUUuVFrLH3s', 'img-content/western/nom-personne.jpg', 1973, 'Ennio Morricone', 'Ennio Morricone, né en 1928, est un compositeur, producteur et chef d''orchestre italien. Il est particulièrement connu pour ses musiques de films, notamment les films de son ami Sergio Leone. Ayant composé la musique de plus de 500 films et récompensé 25 fois dans divers cérémonies dans la catégorie « Meilleure musique de film », sa dernière récompense fut pour le film « Les Huit Salopards » (2015) de Quentin Tarantino.', 0),
(5, 'western', 'Django Unchained', 'https://embed.spotify.com/?uri=spotify%3Auser%3Adjangounchained%3Aplaylist%3A15riquYQZCeeO0AwjQeOzg', 'img-content/western/django-unchained.jpg', 2013, 'Luis Bacalov', 'Luis Enrique Bacalov, né en 1933, est un compositeur de musique de film italien. Dès le début de sa carrière, il compose pour des films de western spaghetti. Il a composé la bande originale de plus de 160 films durant sa carrière. Pour ses compositions, il a été nommé 12 fois dans la catégorie « Meilleur musique de film » et à gagner l’Oscar de la meilleure musique de film en 1996 pour « Le Facteur » (Il postino) de Michael Redford.\r\n', 0),
(6, 'sci-fi', '2001 l''Odyssée de l''espace', 'https://embed.spotify.com/?uri=spotify%3Atrack%3A69YhW203H4dj8oV4xLP3Aj', 'img-content/sci-fi/2001-odyssee.jpg', 1968, 'Richard & Johann Strauss', '2001 l''Odyssée de l''espace film culte de Kubrick, qui use de la suite de valses du "Beau Danube bleu" de Johann Strauss II et du poème symphonique de Richard Strauss "Ainsi parlait Zarathoustra", afin de mettre en avant la musique et les effets sonores qui revêtent une importance particulière, structurant profondément les aspects narratifs et spéculatifs du film, et redéfinissant les liens entre musique et image dans le cinéma de science-fiction contemporain.', 0),
(7, 'sci-fi', 'Star Wars', 'https://embed.spotify.com/?uri=spotify%3Aalbum%3A4U3QXT724KzhhnZ6x2UUn3', 'img-content/sci-fi/star-wars.jpg', 1977, 'John Williams', 'John Williams est un compositeur, chef d''orchestre et pianiste américain né le 8 février 1932 à New York.\r\nOn lui doit le renouveau des bandes originales symphoniques avec ce qui reste son œuvre la plus célèbre : la musique de la saga Star Wars. Compositeur attitré de Steven Spielberg et de George Lucas, Williams a composé au cours d''une carrière qui s''étend sur près de soixante ans, un grand nombre des plus célèbres musiques de films de l''histoire d''Hollywood, notamment Les Dents de la mer, les sagas Star Wars et Indiana Jones, Superman, E.T. l''extra-terrestre, Jurassic Park et les trois premiers films de la saga Harry Potter.', 0),
(8, 'sci-fi', 'Retour vers le futur', 'https://embed.spotify.com/?uri=spotify%3Auser%3A1156868989%3Aplaylist%3A2thXA9GmL6NFw1pPoSK05t', 'img-content/sci-fi/retour-futur.jpg', 1978, 'Alan Silvestri', 'Alan Silvestri (26 mars 1950 à New York) est un compositeur américain de musiques de films, d''origine italienne. Il est surtout connu pour sa collaboration avec le réalisateur Robert Zemeckis sur À la poursuite du diamant vert, la trilogie des Retour vers le futur, Qui veut la peau de Roger Rabbit ?, Forrest Gump, Contact, Seul au monde, Apparences, Le Pôle express, La Légende de Beowulf ou Flight et avec d''autres réalisateurs sur Predator, Abyss et Avengers.', 0),
(9, 'sci-fi', 'Alien', 'https://embed.spotify.com/?uri=spotify%3Aalbum%3A3JlL0Bd3EvhEVRzlIPwTbp', 'img-content/sci-fi/alien.jpg', 1979, 'James Horner', 'James Horner est un compositeur de musique de films américain né le 14 août 1953 à Los Angeles et mort le 22 juin 2015. Il est le compositeur des musiques de certains des plus grands succès cinématographiques depuis les années 1980.  En 1982, il crée la musique originale du film Star Trek 2 : La Colère de Khan, devenant ainsi un compositeur de première importance.\r\nParmi ses œuvres fondatrices, il faut citer les partitions de Brainstorm, La Foire des ténèbres et Krull, toutes trois composées en 1983 et qui l''amènent très vite à travailler sur de grosses productions telles que Aliens de James Cameron ou bien encore Le Nom de la rose de Jean-Jacques Annaud en 1986.', 0),
(10, 'sci-fi', 'Terminator', 'https://embed.spotify.com/?uri=spotify%3Aalbum%3A0zNrBVablisdvocqHWpJ6k', 'img-content/sci-fi/terminator.jpg', 1984, 'Brad Fiedel', 'Brad Fiedel est un compositeur et chanteur américain, né le 10 mars 1951 à New York (État de New York, États-Unis).\r\nIl est notamment connu pour son travail avec le réalisateur James Cameron pour la musique de Terminator et Terminator 2.', 0),
(12, 'sci-fi', 'Matrix', 'https://embed.spotify.com/?uri=spotify%3Aalbum%3A37qsz0ssGQnzA59svY9Vje', 'img-content/sci-fi/matrix.jpg', 1999, 'Don Davis', 'Donald Romain Davis est un compositeur américain né le 4 février 1957 à Anaheim, Californie (États-Unis).\r\n\r\nIl est principalement connu pour avoir composé la musique de la trilogie Matrix réalisée par Andy et Lana Wachowski.', 0),
(13, 'sci-fi', 'Interstellar', 'https://embed.spotify.com/?uri=spotify%3Aalbum%3A7a78GiEowpaCa7ZJs44xUU', 'img-content/sci-fi/interstellar.jpg', 2014, 'Hans Zimmer', 'Hans Zimmer est un compositeur de musique de film né le 12 septembre 1957 à Francfort, en Allemagne. Il est actuellement reconnu comme étant l''un des plus grands compositeurs de musique de film au monde. Rain Man révèle sa musique au grand public et marque l''entrée tonitruante du compositeur sur le sol américain avec une nomination aux Oscars.La composition de son premier film d''animation en 1994 marque un tournant dans sa carrière. En effet pour Le Roi lion de Walt Disney Pictures, il remporte son premier et unique Oscar à ce jour, mais aussi un Golden Globe et un Grammy Award. En plus d''être sa bande originale la plus récompensée, Le Roi lion est aussi la plus vendue (plus de 26 millions de disques).', 0),
(14, 'action', 'James Bond', 'https://embed.spotify.com/?uri=spotify%3Auser%3Askinnymenace%3Aplaylist%3A5fXfad3KG0rB3F6ZwdeEov', 'img-content/action/james-bond.jpg', 1962, 'John Barry (divers)', 'Au fil des années, les films de James Bond d''EON Productions ont accumulé un grand nombre de chansons, dont beaucoup sont considérées comme des classiques de la musique de film. La plus connue est sans doute le James Bond Theme, une musique instrumentale qui apparait dans l''introduction de tous les films. Bien d''autres thèmes ont eu un succès à la hauteur de la série, comme The 007 Theme, Goldfinger, You Only Live Twice, Nobody Does It Better ou For Your Eyes Only. Le James Bond Theme est une musique instrumentale créé par Monty Norman et arrangée puis orchestrée par John Barry.', 0),
(15, 'action', 'Rocky', 'https://embed.spotify.com/?uri=spotify%3Auser%3Aalecvaida%3Aplaylist%3A2XvBct9PdJlQWU2M7Q28rn', 'img-content/action/rocky.jpg', 1976, 'Bill Conti', 'Chef d''orchestre à l''âge de 15 ans, Bill Conti commença à composer pour le cinéma en 1973.\r\nSon premier succès fut, en 1976, la musique du film Rocky, dont le thème Gonna Fly Now deviendra un tube mondialement connu. La saga sera ensuite déclinée en 5 suites, dont Conti signera la musique (à l''exception de Rocky IV).\r\nSouvent associé aux films de Sylvester Stallone, il devient également le collaborateur régulier du réalisateur, John G. Avildsen, notamment avec la saga des Karaté Kid.', 0),
(16, 'action', 'Indiana Jones', 'https://embed.spotify.com/?uri=spotify%3Atrack%3A2wB26YZdCB4BZ5cN8eHKs4', 'img-content/action/indiana-jones.jpg', 1981, 'John Williams', 'John Williams est un compositeur, chef d''orchestre et pianiste américain né le 8 février 1932 à New York.\r\nOn lui doit le renouveau des bandes originales symphoniques avec ce qui reste son œuvre la plus célèbre : la musique de la saga Star Wars. Compositeur attitré de Steven Spielberg et de George Lucas, Williams a composé au cours d''une carrière qui s''étend sur près de soixante ans, un grand nombre des plus célèbres musiques de films de l''histoire d''Hollywood, notamment Les Dents de la mer, les sagas Star Wars et Indiana Jones, Superman, E.T. l''extra-terrestre, Jurassic Park et les trois premiers films de la saga Harry Potter.', 0),
(17, 'action', 'Men in Black', 'https://embed.spotify.com/?uri=spotify%3Aalbum%3A5g2UDPmM7d8itXNojbWF6k', 'img-content/action/men-in-black.jpg', 1997, 'Danny Elfman', 'Danny Elfman, né le 29 mai 1953 à Amarillo (Texas), est un compositeur américain de musique de films, ancien leader du groupe rock et new wave Oingo Boingo. Il a composé la musique de la plupart des films de Tim Burton, de plusieurs films de Sam Raimi. Au cinéma, il a notamment composé les bandes originales de Dick Tracy (1990), Mission impossible (1996), Men in Black (1997), Will Hunting (1997), Chicago (2002), dont les deux premiers Spider-Man. Il a reçu de nombreuses récompenses pour ses compositions originales et a été nommé quatre fois pour l''Oscar de la meilleure musique de film.', 0),
(18, 'action', 'Gladiator', 'https://embed.spotify.com/?uri=spotify%3Aalbum%3A1yqkE2BoMZaQRABJRJT2HZ', 'img-content/action/gladiator.jpg', 2000, 'Hans Zimmer', 'Hans Zimmer est un compositeur de musique de film né le 12 septembre 1957 à Francfort, en Allemagne. Il est actuellement reconnu comme étant l''un des plus grands compositeurs de musique de film au monde. Rain Man révèle sa musique au grand public et marque l''entrée tonitruante du compositeur sur le sol américain avec une nomination aux Oscars.La composition de son premier film d''animation en 1994 marque un tournant dans sa carrière. En effet pour Le Roi lion de Walt Disney Pictures, il remporte son premier et unique Oscar à ce jour, mais aussi un Golden Globe et un Grammy Award. En plus d''être sa bande originale la plus récompensée, Le Roi lion est aussi la plus vendue (plus de 26 millions de disques).', 0),
(19, 'action', 'Pirates des Caraïbes', 'https://embed.spotify.com/?uri=spotify%3Aalbum%3A46co3YFtDUWwq1DiazleHP', 'img-content/action/pirates.jpg', 2002, 'Hans Zimmer', 'Hans Zimmer est un compositeur de musique de film né le 12 septembre 1957 à Francfort, en Allemagne. Il est actuellement reconnu comme étant l''un des plus grands compositeurs de musique de film au monde. Rain Man révèle sa musique au grand public et marque l''entrée tonitruante du compositeur sur le sol américain avec une nomination aux Oscars.La composition de son premier film d''animation en 1994 marque un tournant dans sa carrière. En effet pour Le Roi lion de Walt Disney Pictures, il remporte son premier et unique Oscar à ce jour, mais aussi un Golden Globe et un Grammy Award. En plus d''être sa bande originale la plus récompensée, Le Roi lion est aussi la plus vendue (plus de 26 millions de disques).', 0),
(20, 'action', 'Kill Bill', 'https://embed.spotify.com/?uri=spotify%3Auser%3Astreamingfinn%3Aplaylist%3A4syfNZ3zg0gYIVosL5XdMb', 'img-content/action/kill-bill.jpg', 2003, 'RZA', 'RZA, de son vrai nom Robert Fitzgerald Diggs, né le 5 juillet 1969 à Brooklyn, New York, est un rappeur, producteur, acteur et réalisateur américain, membre fondateur et leader de facto du groupe Wu-Tang Clan. En 1999, il compose (sous le nom de RZA), la bande son du film Ghost Dog : La Voie du samouraï (Ghost Dog: The Way of the Samurai) de Jim Jarmusch. De même, en 2003, il compose deux titres pour le film Kill Bill : Volume 1 de Quentin Tarantino.', 0),
(21, 'action', 'Sin City', 'https://embed.spotify.com/?uri=spotify%3Aalbum%3A6W1KdF4BQpAnCRP4G4XjQB', 'img-content/action/sin-city.jpg', 2005, 'Robert Rodriguez', 'Robert Rodríguez (né le 20 juin 1968 à San Antonio (Texas) est un réalisateur et musicien américain d''origine mexicaine. Il est connu pour tourner des films à petit budget qui rencontrent souvent un grand succès public et dans lesquels il occupe de nombreux « postes ». Guitariste du groupe Chingón, il compose également les musiques de la plupart de ses films.En 2004, il compose quelques musiques pour Kill Bill volume 2 pour son ami Quentin Tarantino. Selon la rumeur, il n''aurait été payé qu''un dollar. En contrepartie, Tarantino viendra une journée filmer une scène de Sin City.', 0),
(22, 'disney', 'Blanche Neige', 'https://embed.spotify.com/?uri=spotify%3Aalbum%3A0vMpIGh2knD4YLkTyIts9D', 'img-content/disney/blanche-neige.jpg', 1937, 'Paul J.Smith', 'Paul J. Smith (né le 30 octobre 1906 à Calumet, Michigan – mort le 25 janvier 1985 à Glendale1) est un compositeur américain. Il a passé une grande partie de sa carrière au sein de Walt Disney Productions, composant de nombreuses musiques pour les courts et longs métrages d''animation.', 0),
(23, 'disney', 'Peter Pan', 'https://embed.spotify.com/?uri=spotify%3Aalbum%3A0p5GACBeBCqu6YVDp8HoVI', 'img-content/disney/peter-pan.jpg', 1953, 'James Newton Howard', 'James Newton Howard est un musicien et compositeur américain né le 9 juin 1951 à Los Angeles (Californie). Il compose principalement des musiques de film. Il a été nommé à maintes reprises pour ses œuvres musicales.', 0),
(24, 'disney', 'Le livre de la jungle', 'https://embed.spotify.com/?uri=spotify%3Aalbum%3A6k3BwalwdZYIxpgGzNH4BP', 'img-content/disney/livre-de-la-jungle.jpg', 1967, 'John Debney', 'John Debney est un compositeur américain né le 18 août 1956 à Glendale, Californie (États-Unis).Il est le fils de Louis Debney, animateur, réalisateur et producteur pour les studios Disney.', 0),
(25, 'disney', 'Les Aristochats', 'https://embed.spotify.com/?uri=spotify%3Aalbum%3A4xP8YdX6dIi649dxAH2PXO', 'img-content/disney/les-aristochats.jpg', 1970, 'George Bruns', 'George Bruns est un compositeur américain, né le 3 juillet 1914 et mort le 23 mai 1983 à Portland (États-Unis). Il travailla sur plusieurs films et attractions Disney.', 0),
(26, 'disney', 'Robin des bois', 'https://embed.spotify.com/?uri=spotify%3Aalbum%3A3IwG92NqebKIcOPrEQzaJn', 'img-content/disney/robin-des-bois.jpg', 1973, 'George Bruns', 'George Bruns est un compositeur américain, né le 3 juillet 1914 et mort le 23 mai 1983 à Portland (États-Unis). Il travailla sur plusieurs films et attractions Disney.', 0),
(27, 'disney', 'Winnie L''ourson', 'https://embed.spotify.com/?uri=spotify%3Aalbum%3A2nzlHKcWjyvvf6tdIkGOs3', 'img-content/disney/winnie-ourson.jpg', 1977, 'Henry Jackman', 'Henry Jackman (né en 1974 à Hillingdon) est un compositeur de musique de film travaillant au studio Remote Control Productions.', 0),
(28, 'disney', 'La petite sirène', 'https://embed.spotify.com/?uri=spotify%3Aalbum%3A6uG53IqMUoIFbDkJ4gCPZj', 'img-content/disney/la-petite-sirene.jpg', 1990, 'Alan Menken', 'Alan Menken est un compositeur américain né le 22 juillet 1949 à New Rochelle, New York.', 0),
(29, 'disney', 'Le Roi Lion', 'https://embed.spotify.com/?uri=spotify%3Atrack%3A4cbs7fuf3K06To0WcLiIY6', 'img-content/disney/le-roi-lion.jpg', 1994, 'Hans Zimmer', 'Hans Zimmer est un compositeur de musique de film né le 12 septembre 1957 à Francfort, en Allemagne. Il est actuellement reconnu comme étant l''un des plus grands compositeurs de musique de film au monde. Rain Man révèle sa musique au grand public et marque l''entrée tonitruante du compositeur sur le sol américain avec une nomination aux Oscars.La composition de son premier film d''animation en 1994 marque un tournant dans sa carrière. En effet pour Le Roi lion de Walt Disney Pictures, il remporte son premier et unique Oscar à ce jour, mais aussi un Golden Globe et un Grammy Award. En plus d''être sa bande originale la plus récompensée, Le Roi lion est aussi la plus vendue (plus de 26 millions de disques).', 0),
(30, 'western', 'Danse avec les loups', 'https://embed.spotify.com/?uri=spotify%3Aalbum%3A0Z4Vrnqe9T959fiFI2Xyax', 'img-content/western/danse-loups.jpg', 1990, 'John Barry', 'Jonathan Barry Prendergast, né le 3 novembre 1933 à York et mort le 30 janvier 2011 à Oyster Bay Long Island (État de New York), est un compositeur britannique de musique de film. Il est connu en particulier pour la musique des James Bond dont il refait le thème, qui devient ainsi «un classique de la bande originale de film ».', 0),
(31, 'western', 'Les 7 mercenaires', 'https://embed.spotify.com/?uri=spotify%3Aalbum%3A4daKlfF0wnq2FvLDcQnuQZ', 'img-content/western/magnificent-seven.jpg', 1960, 'Elmer Bernstein', 'Elmer Bernstein est un compositeur américain, né le 4 avril 1922 à New York et mort le 18 août 2004 à l''âge de 82 ans à Ojai en Californie.\r\nBien que sa partition pour Les Sept Mercenaires soit assurément son œuvre la plus célèbre, il est l''auteur de plus de 250 musiques de films et téléfilms, démontrant son incroyable talent à sublimer les genres. ', 0);

--
-- Index pour les tables exportées
--

--
-- Index pour la table `filmuz`
--
ALTER TABLE `filmuz`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT pour les tables exportées
--

--
-- AUTO_INCREMENT pour la table `filmuz`
--
ALTER TABLE `filmuz`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=32;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
